version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Zipping PHP app for Elastic Beanstalk..."
      - zip -r app.zip . -x "*.git*" "vendor/*" "node_modules/*"
artifacts:
  files:
    - app.zip
