version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0
  build:
    commands:
      - echo "Zipping the app..."
      - zip -r app.zip . -x "*.git*" "vendor/*" "node_modules/*"
artifacts:
  files:
    - app.zip
